import type { ExpoConfig } from 'expo/config';

/**
 * Expo config. All native configuration lives here (and in config plugins),
 * never in ios/ or android/, which are regenerated by `expo prebuild`.
 */
const config: ExpoConfig = {
  name: 'LINKD',
  slug: 'linkd',
  version: '1.0.0',
  orientation: 'portrait',
  scheme: 'linkd',
  userInterfaceStyle: 'automatic',
  icon: './assets/images/icon.png',
  platforms: ['ios', 'android'],
  ios: {
    supportsTablet: false,
    bundleIdentifier: 'com.linkd.app',
  },
  android: {
    package: 'com.linkd.app',
    adaptiveIcon: {
      backgroundColor: '#E6F4FE',
      foregroundImage: './assets/images/android-icon-foreground.png',
      backgroundImage: './assets/images/android-icon-background.png',
      monochromeImage: './assets/images/android-icon-monochrome.png',
    },
    predictiveBackGestureEnabled: false,
  },
  plugins: [
    'expo-router',
    [
      'expo-splash-screen',
      {
        backgroundColor: '#208AEF',
        image: './assets/images/splash-icon.png',
        imageWidth: 76,
      },
    ],
  ],
  experiments: {
    typedRoutes: true,
  },
};

export default config;
