-- Profiles, alerts, and per-recipient delivery for the send-alert Edge Function.
-- Spec: docs/design/sos_alert_flow.md, docs/protocol/supabase_protocol.md (Edge Functions).

-- ---------- profiles: who is in danger, and the callback number contacts are given ----------

create table public.profiles (
  user_id      uuid primary key default auth.uid() references auth.users (id) on delete cascade,
  display_name text not null check (char_length(btrim(display_name)) between 1 and 100),
  -- The user's own number, unverified until SMS verification lands
  phone_e164   text not null check (phone_e164 ~ '^\+[1-9][0-9]{1,14}$'),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

alter table public.profiles enable row level security;
revoke all on public.profiles from anon, authenticated;
grant select on public.profiles to authenticated;
grant insert (display_name, phone_e164), update (display_name, phone_e164) on public.profiles to authenticated;

create policy "own profile: select" on public.profiles
  for select to authenticated using (user_id = (select auth.uid()));
create policy "own profile: insert" on public.profiles
  for insert to authenticated with check (user_id = (select auth.uid()));
create policy "own profile: update" on public.profiles
  for update to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

create trigger profiles_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

-- ---------- alerts and recipients: written only by the server, readable by the owner ----------

create table public.alerts (
  -- Generated by the app so retries are idempotent
  id           uuid primary key,
  user_id      uuid not null references auth.users (id) on delete cascade,
  trigger      text not null check (trigger in ('button', 'inApp', 'linkLoss')),
  triggered_at timestamptz not null,
  latitude     double precision check (latitude between -90 and 90),
  longitude    double precision check (longitude between -180 and 180),
  accuracy_m   real check (accuracy_m >= 0),
  located_at   timestamptz,
  created_at   timestamptz not null default now(),
  check ((latitude is null) = (longitude is null))
);

-- Snapshot of the active contacts at send time, so later contact edits never change who was told.
create table public.alert_recipients (
  alert_id            uuid not null references public.alerts (id) on delete cascade,
  contact_id          uuid references public.emergency_contacts (id) on delete set null,
  name                text not null,
  phone_e164          text not null,
  -- sending = claimed by a send in flight; see claim_alert_recipients
  status              text not null default 'pending' check (status in ('pending', 'sending', 'sent', 'failed')),
  provider_message_id text,
  error               text,
  updated_at          timestamptz not null default now(),
  primary key (alert_id, phone_e164)
);

alter table public.alerts enable row level security;
alter table public.alert_recipients enable row level security;
revoke all on public.alerts, public.alert_recipients from anon, authenticated;
grant select on public.alerts, public.alert_recipients to authenticated;

create policy "own alerts: select" on public.alerts
  for select to authenticated using (user_id = (select auth.uid()));
create policy "own alert recipients: select" on public.alert_recipients
  for select to authenticated
  using (exists (select 1 from public.alerts a where a.id = alert_id and a.user_id = (select auth.uid())));

-- ---------- server-only functions (service role) ----------

/**
 * Records the alert once per id and snapshots the user's active contacts as recipients.
 * Safe to retry. Fails with 42501 if the id already belongs to another user.
 * Returns the sender's profile (null fields if none) and how many recipients the alert has.
 */
create function public.start_alert(
  p_user_id uuid, p_id uuid, p_trigger text, p_triggered_at timestamptz,
  p_latitude double precision, p_longitude double precision, p_accuracy_m real, p_located_at timestamptz
) returns table (display_name text, phone_e164 text, recipient_count int)
language plpgsql set search_path = '' as $$
declare
  owner uuid;
begin
  insert into public.alerts (id, user_id, trigger, triggered_at, latitude, longitude, accuracy_m, located_at)
  values (p_id, p_user_id, p_trigger, p_triggered_at, p_latitude, p_longitude, p_accuracy_m, p_located_at)
  on conflict (id) do nothing;

  if found then
    insert into public.alert_recipients (alert_id, contact_id, name, phone_e164)
    select p_id, c.id, c.name, c.phone_e164
      from public.emergency_contacts c
     where c.user_id = p_user_id and c.status = 'active';
  else
    select a.user_id into owner from public.alerts a where a.id = p_id;
    if owner <> p_user_id then
      raise exception 'alert id belongs to another user' using errcode = 'insufficient_privilege';
    end if;
  end if;

  return query
    select p.display_name, p.phone_e164,
           (select count(*)::int from public.alert_recipients r where r.alert_id = p_id)
      from (select 1) one
      left join public.profiles p on p.user_id = p_user_id;
end $$;

/**
 * Claims the recipients that still need a text and marks them `sending`, atomically, so
 * concurrent retries never text anyone twice. A claim older than 60 s is treated as a crashed
 * send and claimed again: a duplicate text is better than a missed one.
 */
create function public.claim_alert_recipients(p_alert_id uuid)
returns table (phone_e164 text)
language sql set search_path = '' as $$
  update public.alert_recipients r
     set status = 'sending', updated_at = now()
   where r.alert_id = p_alert_id
     and (r.status in ('pending', 'failed')
          or (r.status = 'sending' and r.updated_at < now() - interval '60 seconds'))
  returning r.phone_e164;
$$;

/** Records one recipient's outcome (`sent` or `failed`). A recipient already sent is never downgraded. */
create function public.record_alert_recipient(
  p_alert_id uuid, p_phone_e164 text, p_status text, p_provider_message_id text, p_error text
) returns void
language plpgsql set search_path = '' as $$
begin
  if p_status not in ('sent', 'failed') then
    raise exception 'status must be sent or failed' using errcode = 'invalid_parameter_value';
  end if;
  update public.alert_recipients
     set status = p_status, provider_message_id = p_provider_message_id, error = p_error, updated_at = now()
   where alert_id = p_alert_id and phone_e164 = p_phone_e164 and status <> 'sent';
end $$;

revoke execute on function public.start_alert, public.claim_alert_recipients, public.record_alert_recipient
  from public, anon, authenticated;
grant execute on function public.start_alert, public.claim_alert_recipients, public.record_alert_recipient
  to service_role;
